spring.application.name=tariff
spring.h2.console.enabled=true

# Database URL
spring.datasource.url=jdbc:mysql://tariff.cjk8eumy4w2k.ap-southeast-2.rds.amazonaws.com/tariff
spring.datasource.username=group6
spring.datasource.password=cs203group6

# Driver class (optional - auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect